---

- name: Create an empty directory
  hosts: my-machine2
  remote_user: nikhil

  tasks:
  - name: create an empty file
    file:
      path: "/home/nikhil/newfile1.txt"
      state: touch


  - name: create an empty directory
    file:
      path: "/home/nikhil/Ansible_directory"
      state: directory

